fix: issue #107
slashdevops/idp-scim-sync pull request #108
Opened 2023-05-14 17:26 UTC by christiangda

This should fix issue #107 , but it is hard to test mocking the Google API method https://github.com/slashdevops/idp-scim-sync/issues/107

2023-07-12 15:43 UTC, laurentdelosieresfact requested changes

2023-07-12 15:43 UTC, laurentdelosieresfact commented on pkg/google/google.go
> +	return u, nil
@christiangda why not leaving it as such ? "return u, err" ?

2023-07-12 15:43 UTC, laurentdelosieresfact commented on pkg/google/google.go
> +	return g, nil
@christiangda why not leaving it as such ? "return u, err" ?

2023-07-12 15:43 UTC, laurentdelosieresfact commented on pkg/google/google.go
> +	return m, nil
@christiangda why not leaving it as such ? "return u, err" ?

2023-09-06 16:00 UTC, laurentdelosieresfact commented
Hello @christiangda ,

We have been running the idp-scim with the changes over the past 2 months, and we have not had any issues, everything is running smoothy. Could you merge the PR ? :pray.

Thank you in advance,

2023-09-07 10:49 UTC, snavarro-factorial commented
+1 From my side too; we had no issues of groups being deleted and recreated randomly.

2023-09-10 07:35 UTC, merged